-- Assets are generated by src.generate_assets and loaded by src.database_loader.
-- This file is intentionally valid SQL so Docker init can execute it safely.
SELECT 'smart-metering seed placeholder' AS info;

